//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File_tracking_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int id { get; set; }
        public string Reference_number { get; set; }
        public string Title { get; set; }
        public string Volume_number { get; set; }
        public string Date_opened { get; set; }
        public string Date_closed { get; set; }
        public string File_status { get; set; }
        public string Name_organisation { get; set; }
        public string folio_number { get; set; }
        public string Markout_File_status { get; set; }
    }
}
