//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File_tracking_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark_out
    {
        public int Request_number { get; set; }
        public string Reference_number { get; set; }
        public string File_title { get; set; }
        public string Date_in { get; set; }
        public string Date_out { get; set; }
        public string Volume_number { get; set; }
        public string Dispatch_officer { get; set; }
        public string Requesting_officer { get; set; }
        public string File_status { get; set; }
        public string Markout_File_status { get; set; }
        public string duration_status { get; set; }
    }
}
